# config/app.yml for rails-settings-cached
defaults: &defaults
  email_template: "<html><head></head><body>Lorem Ipsum Text</body></html>"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
